[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "quipu"
description = "Generate invoices in Quipu"
version = "0.1.0"
authors = [{ name = "Aldo Borrero", email = "aldo@aldoborrero.com" }]
license = "MIT"
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "Topic :: Utilities",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
]
[project.urls]
Homepage = "https://github.com/numtide/numtide-invoice-generator"

[project.scripts]
quipu-invoicer = "quipu_invoicer:main"
quipu-cli = "quipu_api.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["quipu_invoicer", "quipu_api"]

[tool.mypy]
python_version = "3.12"
warn_redundant_casts = true
disallow_untyped_calls = true
disallow_untyped_defs = true
no_implicit_optional = true

[[tool.mypy.overrides]]
module = "setuptools.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "quipu.*"
ignore_missing_imports = true
